weights:
  count_by_product: 1
  insert_order: 10
db_config:
  host: 52.32.178.240
  port: 3306
  user: xbench
  password: ""
  database: "sysbench"
  autocommit: False
  connect_timeout: 5
  read_timeout: 10
  write_timeout: 10
  ssl: 0
